services:
  unisphere.api:
    image: ${DOCKER_REGISTRY-}unisphereapi
    build:
      context: .
      dockerfile: UniSphere/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081
    environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://unisphere.aspire-dashboard:18889
        - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  unisphere.sql:
    image: postgres:17.5
    environment:
      POSTGRES_DB: unisphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.containers/postgres/data:/var/lib/postgresql/data
  unisphere.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888