// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using UniSphere.Api.Entities;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Admin_SuperAdmin : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<double>(
                name: "midterm_grade",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "double precision",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<double>(
                name: "final_grade",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "double precision",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AddColumn<MultilingualText>(
                name: "bio",
                schema: "uni_sphere",
                table: "professors",
                type: "jsonb",
                nullable: false);

            migrationBuilder.AddColumn<string>(
                name: "gmail",
                schema: "uni_sphere",
                table: "professors",
                type: "character varying(256)",
                maxLength: 256,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "one_time_code",
                schema: "uni_sphere",
                table: "professors",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "one_time_code_created_date",
                schema: "uni_sphere",
                table: "professors",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "one_time_code_expiration_in_minutes",
                schema: "uni_sphere",
                table: "professors",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "days_to_the_finale",
                schema: "uni_sphere",
                table: "faculties",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.CreateTable(
                name: "admins",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    major_id = table.Column<Guid>(type: "uuid", nullable: false),
                    gmail = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    one_time_code = table.Column<int>(type: "integer", nullable: true),
                    one_time_code_created_date = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    one_time_code_expiration_in_minutes = table.Column<int>(type: "integer", nullable: true),
                    first_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    last_name = table.Column<MultilingualText>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_admins", x => x.id);
                    table.ForeignKey(
                        name: "fk_admins_majors_major_id",
                        column: x => x.major_id,
                        principalSchema: "uni_sphere",
                        principalTable: "majors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "student_statistics",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    student_id = table.Column<Guid>(type: "uuid", nullable: false),
                    number_of_attendance_hours = table.Column<double>(type: "double precision", nullable: false),
                    number_of_attendance_lectures = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_student_statistics", x => x.id);
                    table.ForeignKey(
                        name: "fk_student_statistics_student_credentials_student_id",
                        column: x => x.student_id,
                        principalSchema: "uni_sphere",
                        principalTable: "student_credentials",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "super_admins",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false),
                    gmail = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    one_time_code = table.Column<int>(type: "integer", nullable: true),
                    one_time_code_created_date = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    one_time_code_expiration_in_minutes = table.Column<int>(type: "integer", nullable: true),
                    first_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    last_name = table.Column<MultilingualText>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_super_admins", x => x.id);
                    table.ForeignKey(
                        name: "fk_super_admins_faculties_faculty_id",
                        column: x => x.faculty_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculties",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_admins_major_id",
                schema: "uni_sphere",
                table: "admins",
                column: "major_id");

            migrationBuilder.CreateIndex(
                name: "ix_student_statistics_student_id",
                schema: "uni_sphere",
                table: "student_statistics",
                column: "student_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_super_admins_faculty_id",
                schema: "uni_sphere",
                table: "super_admins",
                column: "faculty_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "admins",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "student_statistics",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "super_admins",
                schema: "uni_sphere");

            migrationBuilder.DropColumn(
                name: "bio",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "gmail",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "one_time_code",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "one_time_code_created_date",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "one_time_code_expiration_in_minutes",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "days_to_the_finale",
                schema: "uni_sphere",
                table: "faculties");

            migrationBuilder.AlterColumn<int>(
                name: "midterm_grade",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "integer",
                nullable: true,
                oldClrType: typeof(double),
                oldType: "double precision",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "final_grade",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "integer",
                nullable: true,
                oldClrType: typeof(double),
                oldType: "double precision",
                oldNullable: true);
        }
    }
}
