// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using UniSphere.Api.Entities;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Enhance_Some_tables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<MultilingualText>(
                name: "description",
                schema: "uni_sphere",
                table: "subjects",
                type: "jsonb",
                nullable: false,
                oldClrType: typeof(MultilingualText),
                oldType: "jsonb",
                oldNullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "is_passed",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldNullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<MultilingualText>(
                name: "description",
                schema: "uni_sphere",
                table: "subjects",
                type: "jsonb",
                nullable: true,
                oldClrType: typeof(MultilingualText),
                oldType: "jsonb");

            migrationBuilder.AlterColumn<bool>(
                name: "is_passed",
                schema: "uni_sphere",
                table: "subject_student_links",
                type: "boolean",
                nullable: true,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldDefaultValue: false);
        }
    }
}
