//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using UniSphere.Api.Entities;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_announcements_tabels : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "faculty_announcement",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    content = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_faculty_announcement", x => x.id);
                    table.ForeignKey(
                        name: "fk_faculty_announcement_faculties_faculty_id",
                        column: x => x.faculty_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculties",
                        principalColumn: "id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "major_announcement",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    content = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    subject_id = table.Column<Guid>(type: "uuid", nullable: false),
                    major_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_major_announcement", x => x.id);
                    table.ForeignKey(
                        name: "fk_major_announcement_majors_major_id",
                        column: x => x.major_id,
                        principalSchema: "uni_sphere",
                        principalTable: "majors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_major_announcement_subjects_subject_id",
                        column: x => x.subject_id,
                        principalSchema: "uni_sphere",
                        principalTable: "subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_faculty_announcement_created_at",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "created_at");

            migrationBuilder.CreateIndex(
                name: "ix_faculty_announcement_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "faculty_id");

            migrationBuilder.CreateIndex(
                name: "ix_major_announcement_created_at",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "created_at");

            migrationBuilder.CreateIndex(
                name: "ix_major_announcement_major_id",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "major_id");

            migrationBuilder.CreateIndex(
                name: "ix_major_announcement_subject_id",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "subject_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "faculty_announcement",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "major_announcement",
                schema: "uni_sphere");
        }
    }
}
