// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Support_for_url : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "type",
                schema: "uni_sphere",
                table: "materials",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "type",
                schema: "uni_sphere",
                table: "materials");
        }
    }
}
