//<auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Fixing_some_errors : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement");

            migrationBuilder.DropForeignKey(
                name: "fk_major_announcement_majors_major_id",
                schema: "uni_sphere",
                table: "major_announcement");

            migrationBuilder.DropForeignKey(
                name: "fk_major_announcement_subjects_subject_id",
                schema: "uni_sphere",
                table: "major_announcement");

            migrationBuilder.DropPrimaryKey(
                name: "pk_major_announcement",
                schema: "uni_sphere",
                table: "major_announcement");

            migrationBuilder.DropPrimaryKey(
                name: "pk_faculty_announcement",
                schema: "uni_sphere",
                table: "faculty_announcement");

            migrationBuilder.RenameTable(
                name: "major_announcement",
                schema: "uni_sphere",
                newName: "major_announcements",
                newSchema: "uni_sphere");

            migrationBuilder.RenameTable(
                name: "faculty_announcement",
                schema: "uni_sphere",
                newName: "faculty_announcements",
                newSchema: "uni_sphere");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcement_subject_id",
                schema: "uni_sphere",
                table: "major_announcements",
                newName: "ix_major_announcements_subject_id");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcement_major_id",
                schema: "uni_sphere",
                table: "major_announcements",
                newName: "ix_major_announcements_major_id");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcement_created_at",
                schema: "uni_sphere",
                table: "major_announcements",
                newName: "ix_major_announcements_created_at");

            migrationBuilder.RenameIndex(
                name: "ix_faculty_announcement_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcements",
                newName: "ix_faculty_announcements_faculty_id");

            migrationBuilder.RenameIndex(
                name: "ix_faculty_announcement_created_at",
                schema: "uni_sphere",
                table: "faculty_announcements",
                newName: "ix_faculty_announcements_created_at");

            migrationBuilder.AddPrimaryKey(
                name: "pk_major_announcements",
                schema: "uni_sphere",
                table: "major_announcements",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_faculty_announcements",
                schema: "uni_sphere",
                table: "faculty_announcements",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_faculty_announcements_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcements",
                column: "faculty_id",
                principalSchema: "uni_sphere",
                principalTable: "faculties",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_major_announcements_majors_major_id",
                schema: "uni_sphere",
                table: "major_announcements",
                column: "major_id",
                principalSchema: "uni_sphere",
                principalTable: "majors",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_major_announcements_subjects_subject_id",
                schema: "uni_sphere",
                table: "major_announcements",
                column: "subject_id",
                principalSchema: "uni_sphere",
                principalTable: "subjects",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_faculty_announcements_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcements");

            migrationBuilder.DropForeignKey(
                name: "fk_major_announcements_majors_major_id",
                schema: "uni_sphere",
                table: "major_announcements");

            migrationBuilder.DropForeignKey(
                name: "fk_major_announcements_subjects_subject_id",
                schema: "uni_sphere",
                table: "major_announcements");

            migrationBuilder.DropPrimaryKey(
                name: "pk_major_announcements",
                schema: "uni_sphere",
                table: "major_announcements");

            migrationBuilder.DropPrimaryKey(
                name: "pk_faculty_announcements",
                schema: "uni_sphere",
                table: "faculty_announcements");

            migrationBuilder.RenameTable(
                name: "major_announcements",
                schema: "uni_sphere",
                newName: "major_announcement",
                newSchema: "uni_sphere");

            migrationBuilder.RenameTable(
                name: "faculty_announcements",
                schema: "uni_sphere",
                newName: "faculty_announcement",
                newSchema: "uni_sphere");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcements_subject_id",
                schema: "uni_sphere",
                table: "major_announcement",
                newName: "ix_major_announcement_subject_id");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcements_major_id",
                schema: "uni_sphere",
                table: "major_announcement",
                newName: "ix_major_announcement_major_id");

            migrationBuilder.RenameIndex(
                name: "ix_major_announcements_created_at",
                schema: "uni_sphere",
                table: "major_announcement",
                newName: "ix_major_announcement_created_at");

            migrationBuilder.RenameIndex(
                name: "ix_faculty_announcements_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement",
                newName: "ix_faculty_announcement_faculty_id");

            migrationBuilder.RenameIndex(
                name: "ix_faculty_announcements_created_at",
                schema: "uni_sphere",
                table: "faculty_announcement",
                newName: "ix_faculty_announcement_created_at");

            migrationBuilder.AddPrimaryKey(
                name: "pk_major_announcement",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_faculty_announcement",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "faculty_id",
                principalSchema: "uni_sphere",
                principalTable: "faculties",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_major_announcement_majors_major_id",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "major_id",
                principalSchema: "uni_sphere",
                principalTable: "majors",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_major_announcement_subjects_subject_id",
                schema: "uni_sphere",
                table: "major_announcement",
                column: "subject_id",
                principalSchema: "uni_sphere",
                principalTable: "subjects",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
