// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Set_Unigunes_ToStudentNumber_And_MajorId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.CreateIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials",
                columns: new[] { "student_number", "major_id" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.CreateIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials",
                columns: new[] { "student_number", "major_id" });
        }
    }
}
