// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class idk_changes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_admins_majors_major_id",
                schema: "uni_sphere",
                table: "admins");

            migrationBuilder.AddColumn<Guid>(
                name: "faculty_id1",
                schema: "uni_sphere",
                table: "super_admins",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_super_admins_faculty_id1",
                schema: "uni_sphere",
                table: "super_admins",
                column: "faculty_id1");

            migrationBuilder.AddForeignKey(
                name: "fk_admins_majors_major_id",
                schema: "uni_sphere",
                table: "admins",
                column: "major_id",
                principalSchema: "uni_sphere",
                principalTable: "majors",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_super_admins_faculties_faculty_id1",
                schema: "uni_sphere",
                table: "super_admins",
                column: "faculty_id1",
                principalSchema: "uni_sphere",
                principalTable: "faculties",
                principalColumn: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_admins_majors_major_id",
                schema: "uni_sphere",
                table: "admins");

            migrationBuilder.DropForeignKey(
                name: "fk_super_admins_faculties_faculty_id1",
                schema: "uni_sphere",
                table: "super_admins");

            migrationBuilder.DropIndex(
                name: "ix_super_admins_faculty_id1",
                schema: "uni_sphere",
                table: "super_admins");

            migrationBuilder.DropColumn(
                name: "faculty_id1",
                schema: "uni_sphere",
                table: "super_admins");

            migrationBuilder.AddForeignKey(
                name: "fk_admins_majors_major_id",
                schema: "uni_sphere",
                table: "admins",
                column: "major_id",
                principalSchema: "uni_sphere",
                principalTable: "majors",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
