// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Connect_professor_to_fculty : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "professor_faculty_links",
                schema: "uni_sphere",
                columns: table => new
                {
                    professor_id = table.Column<Guid>(type: "uuid", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_professor_faculty_links", x => new { x.professor_id, x.faculty_id });
                    table.ForeignKey(
                        name: "fk_professor_faculty_links_faculties_faculty_id",
                        column: x => x.faculty_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculties",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_professor_faculty_links_professors_professor_id",
                        column: x => x.professor_id,
                        principalSchema: "uni_sphere",
                        principalTable: "professors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_professor_faculty_links_faculty_id",
                schema: "uni_sphere",
                table: "professor_faculty_links",
                column: "faculty_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "professor_faculty_links",
                schema: "uni_sphere");
        }
    }
}
