// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using UniSphere.Api.Entities;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Modify_lecutre_tables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "lecturer_name",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropColumn(
                name: "subject_name",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.AddColumn<Guid>(
                name: "professor_id",
                schema: "uni_sphere",
                table: "lectures",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "subject_id",
                schema: "uni_sphere",
                table: "lectures",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "ix_lectures_professor_id",
                schema: "uni_sphere",
                table: "lectures",
                column: "professor_id");

            migrationBuilder.CreateIndex(
                name: "ix_lectures_subject_id",
                schema: "uni_sphere",
                table: "lectures",
                column: "subject_id");

            migrationBuilder.AddForeignKey(
                name: "fk_lectures_professors_professor_id",
                schema: "uni_sphere",
                table: "lectures",
                column: "professor_id",
                principalSchema: "uni_sphere",
                principalTable: "professors",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "fk_lectures_subjects_subject_id",
                schema: "uni_sphere",
                table: "lectures",
                column: "subject_id",
                principalSchema: "uni_sphere",
                principalTable: "subjects",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_lectures_professors_professor_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropForeignKey(
                name: "fk_lectures_subjects_subject_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropIndex(
                name: "ix_lectures_professor_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropIndex(
                name: "ix_lectures_subject_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropColumn(
                name: "professor_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.DropColumn(
                name: "subject_id",
                schema: "uni_sphere",
                table: "lectures");

            migrationBuilder.AddColumn<MultilingualText>(
                name: "lecturer_name",
                schema: "uni_sphere",
                table: "lectures",
                type: "jsonb",
                nullable: false);

            migrationBuilder.AddColumn<MultilingualText>(
                name: "subject_name",
                schema: "uni_sphere",
                table: "lectures",
                type: "jsonb",
                nullable: false);
        }
    }
}
