//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_scheduleLabLinks : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "schedule_lab_links",
                schema: "uni_sphere",
                columns: table => new
                {
                    schedule_id = table.Column<Guid>(type: "uuid", nullable: false),
                    lab_id = table.Column<Guid>(type: "uuid", nullable: false),
                    start_time = table.Column<TimeSpan>(type: "interval", nullable: false),
                    end_time = table.Column<TimeSpan>(type: "interval", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_schedule_lab_links", x => new { x.schedule_id, x.lab_id });
                    table.ForeignKey(
                        name: "fk_schedule_lab_links_labs_lab_id",
                        column: x => x.lab_id,
                        principalSchema: "uni_sphere",
                        principalTable: "labs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_schedule_lab_links_schedules_schedule_id",
                        column: x => x.schedule_id,
                        principalSchema: "uni_sphere",
                        principalTable: "schedules",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_schedule_lab_links_lab_id",
                schema: "uni_sphere",
                table: "schedule_lab_links",
                column: "lab_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "schedule_lab_links",
                schema: "uni_sphere");
        }
    }
}
