// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Support_for_images_announcement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "faculty_announcement_images",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    faculty_announcement_id = table.Column<Guid>(type: "uuid", nullable: false),
                    url = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_faculty_announcement_images", x => x.id);
                    table.ForeignKey(
                        name: "fk_faculty_announcement_images_faculty_announcements_faculty_a",
                        column: x => x.faculty_announcement_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculty_announcements",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_faculty_announcement_images_faculty_announcement_id",
                schema: "uni_sphere",
                table: "faculty_announcement_images",
                column: "faculty_announcement_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "faculty_announcement_images",
                schema: "uni_sphere");
        }
    }
}
