//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Change_onDelete_forAnnouncements_tables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement");

            migrationBuilder.AddForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "faculty_id",
                principalSchema: "uni_sphere",
                principalTable: "faculties",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement");

            migrationBuilder.AddForeignKey(
                name: "fk_faculty_announcement_faculties_faculty_id",
                schema: "uni_sphere",
                table: "faculty_announcement",
                column: "faculty_id",
                principalSchema: "uni_sphere",
                principalTable: "faculties",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
