// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_pass_grade : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<double>(
                name: "pass_grade",
                schema: "uni_sphere",
                table: "subjects",
                type: "double precision",
                nullable: false,
                defaultValue: 70.0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "pass_grade",
                schema: "uni_sphere",
                table: "subjects");
        }
    }
}
