// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class random_update : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_schedules_major_id",
                schema: "uni_sphere",
                table: "schedules");

            migrationBuilder.CreateIndex(
                name: "ix_schedules_major_id_year_schedule_date",
                schema: "uni_sphere",
                table: "schedules",
                columns: new[] { "major_id", "year", "schedule_date" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_schedules_major_id_year_schedule_date",
                schema: "uni_sphere",
                table: "schedules");

            migrationBuilder.CreateIndex(
                name: "ix_schedules_major_id",
                schema: "uni_sphere",
                table: "schedules",
                column: "major_id");
        }
    }
}
