// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class change_grade_field_type : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<double>(
                name: "midterm_grade",
                schema: "uni_sphere",
                table: "subjects",
                type: "double precision",
                nullable: false,
                defaultValue: 30.0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldDefaultValue: 30);

            migrationBuilder.AlterColumn<double>(
                name: "final_grade",
                schema: "uni_sphere",
                table: "subjects",
                type: "double precision",
                nullable: false,
                defaultValue: 70.0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldDefaultValue: 70);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "midterm_grade",
                schema: "uni_sphere",
                table: "subjects",
                type: "integer",
                nullable: false,
                defaultValue: 30,
                oldClrType: typeof(double),
                oldType: "double precision",
                oldDefaultValue: 30.0);

            migrationBuilder.AlterColumn<int>(
                name: "final_grade",
                schema: "uni_sphere",
                table: "subjects",
                type: "integer",
                nullable: false,
                defaultValue: 70,
                oldClrType: typeof(double),
                oldType: "double precision",
                oldDefaultValue: 70.0);
        }
    }
}
