// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Update_Student_Tables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "email",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.AlterColumn<string>(
                name: "student_number",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "image",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500);

            migrationBuilder.AddColumn<DateTime>(
                name: "one_time_code_created_date",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "one_time_code_expiration_in_minutes",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials",
                columns: new[] { "student_number", "major_id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_student_credentials_student_number_major_id",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.DropColumn(
                name: "one_time_code_created_date",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.DropColumn(
                name: "one_time_code_expiration_in_minutes",
                schema: "uni_sphere",
                table: "student_credentials");

            migrationBuilder.AlterColumn<string>(
                name: "student_number",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100);

            migrationBuilder.AlterColumn<string>(
                name: "image",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100);

            migrationBuilder.AlterColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500,
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "email",
                schema: "uni_sphere",
                table: "student_credentials",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");
        }
    }
}
