// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using UniSphere.Api.Entities;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Create_initail_migration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "uni_sphere");

            migrationBuilder.CreateTable(
                name: "enrollment_statuses",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_enrollment_statuses", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "instructors",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    last_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    father_name = table.Column<MultilingualText>(type: "jsonb", nullable: true),
                    email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    password = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    image = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_instructors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "labs",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    description = table.Column<MultilingualText>(type: "jsonb", nullable: true),
                    image = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_labs", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "professors",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    last_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    image = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_professors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "universities",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    type = table.Column<MultilingualText>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_universities", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "instructor_lab_link",
                schema: "uni_sphere",
                columns: table => new
                {
                    instructor_id = table.Column<Guid>(type: "uuid", nullable: false),
                    lab_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_instructor_lab_link", x => new { x.instructor_id, x.lab_id });
                    table.ForeignKey(
                        name: "fk_instructor_lab_link_instructors_instructor_id",
                        column: x => x.instructor_id,
                        principalSchema: "uni_sphere",
                        principalTable: "instructors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_instructor_lab_link_labs_lab_id",
                        column: x => x.lab_id,
                        principalSchema: "uni_sphere",
                        principalTable: "labs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "faculties",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    university_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_faculties", x => x.id);
                    table.ForeignKey(
                        name: "fk_faculties_universities_university_id",
                        column: x => x.university_id,
                        principalSchema: "uni_sphere",
                        principalTable: "universities",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "majors",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false),
                    number_of_years = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_majors", x => x.id);
                    table.ForeignKey(
                        name: "fk_majors_faculties_faculty_id",
                        column: x => x.faculty_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculties",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "schedules",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    major_id = table.Column<Guid>(type: "uuid", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    schedule_date = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_schedules", x => x.id);
                    table.ForeignKey(
                        name: "fk_schedules_faculties_faculty_id",
                        column: x => x.faculty_id,
                        principalSchema: "uni_sphere",
                        principalTable: "faculties",
                        principalColumn: "id");
                    table.ForeignKey(
                        name: "fk_schedules_majors_major_id",
                        column: x => x.major_id,
                        principalSchema: "uni_sphere",
                        principalTable: "majors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "student_credentials",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false),
                    major_id = table.Column<Guid>(type: "uuid", nullable: false),
                    email = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    one_time_code = table.Column<int>(type: "integer", nullable: true),
                    first_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    last_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    father_name = table.Column<MultilingualText>(type: "jsonb", nullable: true),
                    year = table.Column<int>(type: "integer", nullable: false),
                    enrollment_status_id = table.Column<Guid>(type: "uuid", nullable: false),
                    image = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_student_credentials", x => new { x.id, x.faculty_id });
                    table.ForeignKey(
                        name: "fk_student_credentials_enrollment_statuses_enrollment_status_id",
                        column: x => x.enrollment_status_id,
                        principalSchema: "uni_sphere",
                        principalTable: "enrollment_statuses",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_student_credentials_majors_major_id",
                        column: x => x.major_id,
                        principalSchema: "uni_sphere",
                        principalTable: "majors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "subjects",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    major_id = table.Column<Guid>(type: "uuid", nullable: false),
                    lab_id = table.Column<Guid>(type: "uuid", nullable: true),
                    description = table.Column<MultilingualText>(type: "jsonb", nullable: true),
                    year = table.Column<int>(type: "integer", nullable: false),
                    semester = table.Column<int>(type: "integer", nullable: false),
                    midterm_grade = table.Column<int>(type: "integer", nullable: false, defaultValue: 30),
                    final_grade = table.Column<int>(type: "integer", nullable: false, defaultValue: 70),
                    is_lab_required = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    is_multiple_choice = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    is_open_book = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    image = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subjects", x => x.id);
                    table.ForeignKey(
                        name: "fk_subjects_labs_lab_id",
                        column: x => x.lab_id,
                        principalSchema: "uni_sphere",
                        principalTable: "labs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_subjects_majors_major_id",
                        column: x => x.major_id,
                        principalSchema: "uni_sphere",
                        principalTable: "majors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "lectures",
                schema: "uni_sphere",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    schedule_id = table.Column<Guid>(type: "uuid", nullable: false),
                    subject_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    lecturer_name = table.Column<MultilingualText>(type: "jsonb", nullable: false),
                    start_time = table.Column<TimeSpan>(type: "interval", nullable: false),
                    end_time = table.Column<TimeSpan>(type: "interval", nullable: false),
                    lecture_hall = table.Column<MultilingualText>(type: "jsonb", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_lectures", x => x.id);
                    table.ForeignKey(
                        name: "fk_lectures_schedules_schedule_id",
                        column: x => x.schedule_id,
                        principalSchema: "uni_sphere",
                        principalTable: "schedules",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "subject_professor_links",
                schema: "uni_sphere",
                columns: table => new
                {
                    subject_id = table.Column<Guid>(type: "uuid", nullable: false),
                    professor_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subject_professor_links", x => new { x.subject_id, x.professor_id });
                    table.ForeignKey(
                        name: "fk_subject_professor_links_professors_professor_id",
                        column: x => x.professor_id,
                        principalSchema: "uni_sphere",
                        principalTable: "professors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_subject_professor_links_subjects_subject_id",
                        column: x => x.subject_id,
                        principalSchema: "uni_sphere",
                        principalTable: "subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "subject_student_links",
                schema: "uni_sphere",
                columns: table => new
                {
                    subject_id = table.Column<Guid>(type: "uuid", nullable: false),
                    student_id = table.Column<Guid>(type: "uuid", nullable: false),
                    faculty_id = table.Column<Guid>(type: "uuid", nullable: false),
                    attempt_number = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    midterm_grade = table.Column<int>(type: "integer", nullable: true),
                    final_grade = table.Column<int>(type: "integer", nullable: true),
                    is_currently_enrolled = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    is_passed = table.Column<bool>(type: "boolean", nullable: true),
                    notes = table.Column<MultilingualText>(type: "jsonb", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_subject_student_links", x => new { x.subject_id, x.student_id, x.faculty_id });
                    table.ForeignKey(
                        name: "fk_subject_student_links_student_credentials_student_id_facult",
                        columns: x => new { x.student_id, x.faculty_id },
                        principalSchema: "uni_sphere",
                        principalTable: "student_credentials",
                        principalColumns: new[] { "id", "faculty_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_subject_student_links_subjects_subject_id",
                        column: x => x.subject_id,
                        principalSchema: "uni_sphere",
                        principalTable: "subjects",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_faculties_university_id",
                schema: "uni_sphere",
                table: "faculties",
                column: "university_id");

            migrationBuilder.CreateIndex(
                name: "ix_instructor_lab_link_lab_id",
                schema: "uni_sphere",
                table: "instructor_lab_link",
                column: "lab_id");

            migrationBuilder.CreateIndex(
                name: "ix_lectures_schedule_id",
                schema: "uni_sphere",
                table: "lectures",
                column: "schedule_id");

            migrationBuilder.CreateIndex(
                name: "ix_majors_faculty_id",
                schema: "uni_sphere",
                table: "majors",
                column: "faculty_id");

            migrationBuilder.CreateIndex(
                name: "ix_schedules_faculty_id",
                schema: "uni_sphere",
                table: "schedules",
                column: "faculty_id");

            migrationBuilder.CreateIndex(
                name: "ix_schedules_major_id",
                schema: "uni_sphere",
                table: "schedules",
                column: "major_id");

            migrationBuilder.CreateIndex(
                name: "ix_student_credentials_enrollment_status_id",
                schema: "uni_sphere",
                table: "student_credentials",
                column: "enrollment_status_id");

            migrationBuilder.CreateIndex(
                name: "ix_student_credentials_major_id",
                schema: "uni_sphere",
                table: "student_credentials",
                column: "major_id");

            migrationBuilder.CreateIndex(
                name: "ix_subject_professor_links_professor_id",
                schema: "uni_sphere",
                table: "subject_professor_links",
                column: "professor_id");

            migrationBuilder.CreateIndex(
                name: "ix_subject_student_links_student_id_faculty_id",
                schema: "uni_sphere",
                table: "subject_student_links",
                columns: new[] { "student_id", "faculty_id" });

            migrationBuilder.CreateIndex(
                name: "ix_subjects_lab_id",
                schema: "uni_sphere",
                table: "subjects",
                column: "lab_id");

            migrationBuilder.CreateIndex(
                name: "ix_subjects_major_id",
                schema: "uni_sphere",
                table: "subjects",
                column: "major_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "instructor_lab_link",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "lectures",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "subject_professor_links",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "subject_student_links",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "instructors",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "schedules",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "professors",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "student_credentials",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "subjects",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "enrollment_statuses",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "labs",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "majors",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "faculties",
                schema: "uni_sphere");

            migrationBuilder.DropTable(
                name: "universities",
                schema: "uni_sphere");
        }
    }
}
