// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniSphere.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Identity_Id : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "system_controllers",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "super_admins",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "professors",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "identity_id",
                schema: "uni_sphere",
                table: "admins",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "identity_id",
                schema: "uni_sphere",
                table: "system_controllers");

            migrationBuilder.DropColumn(
                name: "identity_id",
                schema: "uni_sphere",
                table: "super_admins");

            migrationBuilder.DropColumn(
                name: "identity_id",
                schema: "uni_sphere",
                table: "professors");

            migrationBuilder.DropColumn(
                name: "identity_id",
                schema: "uni_sphere",
                table: "admins");
        }
    }
}
