# This is a generated file. Not intended for manual editing.
services:
  unisphere.api:
    build:
      context: "C:\\Users\\Fat7i\\graduationProject\\UniShpereApi\\UniSphere"
      dockerfile: "UniSphere/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "unisphereapi:dev"
    ports:
    - "127.0.0.1:50630:57000"
    - "127.0.0.1:50631:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "C:\\Users\\Fat7i\\graduationProject\\UniShpereApi\\UniSphere\\UniSphere:/app:rw"
    - "C:\\Users\\Fat7i\\graduationProject\\UniShpereApi\\UniSphere:/src:rw"
    - "C:\\Users\\Fat7i\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Fat7i\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.2\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.1.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Fat7i\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_6_16_22_20_47:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
